Add PrettyShow, and make all the output pretty-printed

diff --git a/fco/Makefile b/fco/Makefile
--- a/fco/Makefile
+++ b/fco/Makefile
@@ -5,6 +5,7 @@ sources = \
 	ASTPasses.hs \
 	Parse.hs \
 	Pass.hs \
+	PrettyShow.hs \
 	PT.hs \
 	PTPasses.hs \
 	SExpression.hs \
@@ -19,10 +20,10 @@ tests = $(wildcard test*.occ)
 test: fco $(tests)
 	@set -e; for x in $(tests); do \
 		echo -n "$$x: " ; \
-		if ! ./fco --raw-parse-tree $$x >/dev/null ; then \
+		if ! ./fco --parse-tree $$x >$$x.log 2>&1 ; then \
 			echo "parse failed" ; \
-		elif ! ./fco --ast $$x >/dev/null ; then \
-			echo "ast failed" ; \
+		elif ! ./fco -v $$x >$$x.log 2>&1 ; then \
+			echo "full failed" ; \
 		else \
 			echo "ok" ; \
 		fi ; \
